# .github/release.yml

changelog:
  categories:
    - title: ğŸ•ï¸  Features
      labels:
        - '*'
      exclude:
      labels:
        - dependencies
    - title: ğŸ‘’ Dependencies
      labels:
        - dependencies
