# .github/release.yml
on:
  push:
    branches:
    - main
    
changelog:
  categories:
    - title: ğŸ•ï¸  Features
      labels:
        - '*'
      exclude:
      labels:
        - dependencies
    - title: ğŸ‘’ Dependencies
      labels:
        - dependencies
